# Generated by Django 3.1.2 on 2020-10-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prog_y_proy',
            old_name='tiempo_eje',
            new_name='inicio',
        ),
    ]
