# Generated by Django 3.1.2 on 2020-10-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0002_auto_20201015_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prog_y_proy',
            name='inicio',
        ),
    ]
