# Generated by Django 3.1.2 on 2020-10-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0003_remove_prog_y_proy_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog_y_proy',
            name='acciones_reali',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='area_inter',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='beneficiarios',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='factores_neg',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='factores_pos',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='lecciones_apre',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='metodo_imple',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='objetivo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='resul_alcan',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='prog_y_proy',
            name='resul_espera',
            field=models.CharField(max_length=700),
        ),
    ]
