# Generated by Django 3.1.2 on 2020-10-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0005_donantes_municipios_tipologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prog_y_proy',
            name='donante',
        ),
        migrations.AddField(
            model_name='prog_y_proy',
            name='donante',
            field=models.ManyToManyField(to='caritassm.donantes'),
        ),
        migrations.RemoveField(
            model_name='prog_y_proy',
            name='municipio',
        ),
        migrations.AddField(
            model_name='prog_y_proy',
            name='municipio',
            field=models.ManyToManyField(to='caritassm.municipios'),
        ),
        migrations.RemoveField(
            model_name='prog_y_proy',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='prog_y_proy',
            name='tipologia',
            field=models.ManyToManyField(to='caritassm.tipologia'),
        ),
    ]
