# Generated by Django 3.1.2 on 2020-10-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0006_auto_20201015_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prog_y_proy',
        ),
    ]
