# Generated by Django 3.1.2 on 2020-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritassm', '0009_boletines_ofertas_empleo_recursos_visuales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas_empleo',
            name='actualizacion',
        ),
        migrations.RemoveField(
            model_name='ofertas_empleo',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='ofertas_empleo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='ofertas_empleo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='empleos'),
        ),
    ]
